/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrimeshesIndexRouteImport } from './routes/trimeshes/index'
import { Route as TransformationsIndexRouteImport } from './routes/transformations/index'
import { Route as ShadingIndexRouteImport } from './routes/shading/index'
import { Route as RaytracingIndexRouteImport } from './routes/raytracing/index'
import { Route as CurvesIndexRouteImport } from './routes/curves/index'
import { Route as CompositingIndexRouteImport } from './routes/compositing/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrimeshesIndexRoute = TrimeshesIndexRouteImport.update({
  id: '/trimeshes/',
  path: '/trimeshes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationsIndexRoute = TransformationsIndexRouteImport.update({
  id: '/transformations/',
  path: '/transformations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadingIndexRoute = ShadingIndexRouteImport.update({
  id: '/shading/',
  path: '/shading/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaytracingIndexRoute = RaytracingIndexRouteImport.update({
  id: '/raytracing/',
  path: '/raytracing/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurvesIndexRoute = CurvesIndexRouteImport.update({
  id: '/curves/',
  path: '/curves/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositingIndexRoute = CompositingIndexRouteImport.update({
  id: '/compositing/',
  path: '/compositing/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compositing/': typeof CompositingIndexRoute
  '/curves/': typeof CurvesIndexRoute
  '/raytracing/': typeof RaytracingIndexRoute
  '/shading/': typeof ShadingIndexRoute
  '/transformations/': typeof TransformationsIndexRoute
  '/trimeshes/': typeof TrimeshesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compositing': typeof CompositingIndexRoute
  '/curves': typeof CurvesIndexRoute
  '/raytracing': typeof RaytracingIndexRoute
  '/shading': typeof ShadingIndexRoute
  '/transformations': typeof TransformationsIndexRoute
  '/trimeshes': typeof TrimeshesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compositing/': typeof CompositingIndexRoute
  '/curves/': typeof CurvesIndexRoute
  '/raytracing/': typeof RaytracingIndexRoute
  '/shading/': typeof ShadingIndexRoute
  '/transformations/': typeof TransformationsIndexRoute
  '/trimeshes/': typeof TrimeshesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compositing/'
    | '/curves/'
    | '/raytracing/'
    | '/shading/'
    | '/transformations/'
    | '/trimeshes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compositing'
    | '/curves'
    | '/raytracing'
    | '/shading'
    | '/transformations'
    | '/trimeshes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compositing/'
    | '/curves/'
    | '/raytracing/'
    | '/shading/'
    | '/transformations/'
    | '/trimeshes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompositingIndexRoute: typeof CompositingIndexRoute
  CurvesIndexRoute: typeof CurvesIndexRoute
  RaytracingIndexRoute: typeof RaytracingIndexRoute
  ShadingIndexRoute: typeof ShadingIndexRoute
  TransformationsIndexRoute: typeof TransformationsIndexRoute
  TrimeshesIndexRoute: typeof TrimeshesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trimeshes/': {
      id: '/trimeshes/'
      path: '/trimeshes'
      fullPath: '/trimeshes/'
      preLoaderRoute: typeof TrimeshesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformations/': {
      id: '/transformations/'
      path: '/transformations'
      fullPath: '/transformations/'
      preLoaderRoute: typeof TransformationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shading/': {
      id: '/shading/'
      path: '/shading'
      fullPath: '/shading/'
      preLoaderRoute: typeof ShadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raytracing/': {
      id: '/raytracing/'
      path: '/raytracing'
      fullPath: '/raytracing/'
      preLoaderRoute: typeof RaytracingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curves/': {
      id: '/curves/'
      path: '/curves'
      fullPath: '/curves/'
      preLoaderRoute: typeof CurvesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositing/': {
      id: '/compositing/'
      path: '/compositing'
      fullPath: '/compositing/'
      preLoaderRoute: typeof CompositingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompositingIndexRoute: CompositingIndexRoute,
  CurvesIndexRoute: CurvesIndexRoute,
  RaytracingIndexRoute: RaytracingIndexRoute,
  ShadingIndexRoute: ShadingIndexRoute,
  TransformationsIndexRoute: TransformationsIndexRoute,
  TrimeshesIndexRoute: TrimeshesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
